### ISSUE TITLE
Custom dataloader for scvi-tools

### ISSUE THREAD

**Issue by canergen** [laminlabs/lamindb#1826]
Hi, as discussed in our recent meeting, we can work with custom dataloaders within scvi-tools. It requires being a torch DataModule that loads dictionaries of keyword arguments for each mini batch. We have a working example for CELLXGENE census: https://github.com/chanzuckerberg/cellxgene-census/blob/ebezzi/census-scvi-datamodule/api/python/notebooks/experimental/pytorch_loader_scvi.ipynb (see imports to find the actual datamodule code). You will find that the notebook requires custom code to load and save models. We have built on top of this solution and changed the scvi-tools code to work without an registered AnnData object. I'm setting up a Colab notebook currently with our code and will update here.
Next steps would be feedback to our setup_registry function that takes a datamodule and populates all fields within an scvi-tools model. We currently only support scvi and would like to support more models. I expect that this will be joint effort as things might break outside of scvi-tools (for sure things will not work for multimodal - totalVI or multiVI models).

**Comment by canergen** [comment]
@jkobject Concerning scDataloader, it is currently setup for BERT like loading using a max_len argument. I assume it loads for every cell the 1000 most expressed genes. This structure is not allowed for scvi-tools (we expect the same genes being represented for all cells). Can you provide some help about the how argument?

**Comment by falexwolf** [comment]
Thanks for opening the issue, here!

Can you confirm the objective? By leveraging `MappedCollection` (or its `scdataloader` wrapper), you'd like to be more flexible regarding the storage backend so that you don't necessarily rely on a gigantic tiledbsoma but could also train on a collection of h5ads or parquets.

If so, can you help clarify what _exactly_ is needed from `MappedCollection` so that you could run scvi on it? Is below everything you want from us as an interface for `MappedCollection`?

> It requires being a torch DataModule that loads dictionaries of keyword arguments for each mini batch.

**Comment by Koncopd** [comment]
@canergen if we integrate the underlying `MappedCollection`, that should not be a problem. `MappedCollection` can return all genes (outer or inner join).

**Comment by jkobject** [comment]
Hello All, I will get back to you in a week about this and potential updates to scDataLoader to make it fully in line with scvi-tools. I have already made a PR on the scverse community packages https://github.com/scverse/ecosystem-packages/pull/195 so maybe this discussion will find a better place in this PR?

scDataloader is setup to work in multiple ways to adapt to the new geneformer, scGPT and scPRINT models out there which don't always get the same set of genes. U However it also works if choosing always the same set of genes. how is a parameter for the Collator and is defined in its documentation here:
https://github.com/jkobject/scDataLoader/blob/main/scdataloader/collator.py
you can use "some" to only use a predefined set of genes, "most expr" to only use the most expr genes per cell, "random exp" to only use some randomly expr genes per cell.

If you know which genes you want to use you can use "some" and pass a list of genes, e.g.

```python
from scdataloader import DataModule
import tqdm

datamodule = DataModule(
    collection_name=NAME,
    organisms=["NCBITaxon:9606"], #organism that we will work on
    how="some", # for the collator (most expr genes in the full dataset only will be selected)
    genelist=most_variable_genes_in_data, #not recommended (as it will highlight batch effects)
    batch_size=64,
    num_workers=1,
    validation_split=0.1,
    test_split=0)
 ```

**Comment by canergen** [comment]
> Can you confirm the objective? I understand that by leveraging MappedCollection (or its scdataloader wrapper), you'd like to be more flexible regarding the storage backend so that you don't necessarily rely on a gigantic tiledbsoma but could also train on a collection of h5ads or parquets.

The current comparison is to a huge h5ad file, which doesn't scale to more than 100 million cells (and is already more expensive below these numbers). While we have support for CELLXGENE census we don't support all tiledbsoma databases and CxG census is restrictive in extending it to the whole scvi-tools library..

I assume both dataloaders are in line with our requirements (providing a pipeline of dictionary values). My take is that MappedCollection can provide a dictionary with categorical/integer/float values for every obs column in the underlying AnnData object. However, there are some details.
Missing pieces: We won't provide any validation for custom dataloader (like is the data really count data, is the list of celltype labels or categories in line with the registry). This is not strictly required in our perspective but if you want this feature handling it in the underlying data format can be much better optimized than across formats.
We require a dictionary of celltype labels/batches to integer categorical codes that needs to be stored with the dataloader. The scvi-tools model only take the integer values not the categories (setup_datamodule function within https://colab.research.google.com/drive/10sXec_TicMKtLA6hMcgfkado-FgoNKxw#scrollTo=jiksMKJdlGdK - it doesn't install correctly yet as I have issues with the typing of the CZI code).
Is there support of MuData within MappedCollection. How would you support multimodal (ATAC+RNA+protein data). Currently, we are restricted in terms of input data to the CELLXGENE census with obviously no multimodal collections. I assume large-scale models in the coming year will contain multimodal data.

**Comment by jkobject** [comment]
I am not sure I understand everything, but you seem to say that scdataloader is already in line with scvi-tools, but we need to enforce that its other elements in the output dictionary, e.g., class / batch... are categoricals encoded with integers. The function is already there, and in my example and current use case, everything is transformed so that the encoding is available via the "decoders" property of the datamodule or the "encoder" property of the pytorch datasets.

Given how the mapped collection is implemented, multimodal data is quite straightforward. It just amounts to accessing another field of the underlying H5ad format. For the user, it would receive an 'X_rna', 'X_atac', ... in the output dictionary of tensors instead of just the 'X'.

**Comment by Koncopd** [comment]
We now have an example of how to use `MappedCollection` with `scvi-tools`-based models here https://lamin.ai/laminlabs/cellxgene/transform/d1kl7wobCO1H0005

**Comment by canergen** [comment]
Nice, any reason to not use scDataLoader. For us tests with it are not going smoothely and the CZI dataloader are not maintained - see current failing tests at https://github.com/scverse/scvi-tools/actions/runs/12492962614/job/34860858978?pr=2932. How to you plan to distribute the code? Do you mind us copy-pasting it to our tests? The changes in that PR hopefully allow saving/loading/arches-mapping with dataloaders.

**Comment by Koncopd** [comment]
@falexwolf how do we want to distribute an `scvi`-compatible datamodule from https://lamin.ai/laminlabs/cellxgene/transform/d1kl7wobCO1H0005 ? It requires `pytorch-lightning` , so we shouldn't include it into `lamindb`. Also it is not really  production-ready code, just an ad-hoc example of usage.

@canergen 
>How do I get a list of gene names sorted similarly as the output of collection.mapped (AnnData's adata.vars)?
They are in `.var_joint`.

**Comment by falexwolf** [comment]
Yeah, let's discuss distribution in the upcoming days -- ideas are welcome. Copy-pasting is a good interim solution but of course I hope we can get to something more robust.

**Comment by canergen** [comment]
Hi, I had to write an inference Dataloader that also executes on_before_batch_transfer (not sure how you handle it in scGen but scvi-tools models don't use lightning for inference but iterate over the dataloader). This part is working now. ScArches and reloading models with AnnData is working as well. In the long run, it would make sense to sync scGen to the underlying changes in scvi-tools. You can find the rewritten DataLoader in https://github.com/scverse/scvi-tools/blob/9767b8c5a4ea59aee7c742c09187158963ea8ace/tests/dataloaders/test_custom_dataloader.py#L22.

From my side, we would hope to create a tutorial on how to set up a CustomDataLoader. We could have the code in scvi-tools/data (maybe _utils.py maybe it's own file) but the core idea was to have CustomDataloader within external packages.

There are some missing pieces still:
- ScANVI requires to see all entries of the cell-type column (ad.obs[LABEL_KEY]). What's the most efficient way to get an obs column from the MappedCollection joint object? My understanding of the unlabeled column in collection.mapped is that you assign a value of -1. ScANVI and similar models expect a value of n_labels (last integer) for these entries. Do you have any preference on how to adjust it (likely in the `on_before_batch_transfer` call?
- We need a smaller file than the current one for testing, currently `ln.Collection.get(name="covid_normal_lung`. Additionally, we need access to count data outside of adata.raw.X. Could you create a public artifact (it can be the COVID data subset to 10k cells and with count data in layers.counts.
- Figuring out how to best set up a validation dataloader is still open.

**Comment by Koncopd** [comment]
>ScANVI requires to see all entries of the cell-type column (ad.obs[LABEL_KEY]). What's the most efficient way to get an obs column from the MappedCollection joint object?

Do you need the full column, not only categories? If yes, then it can be done via `.get_merged_labels(LABEL_KEY)`.

>My understanding of the unlabeled column in collection.mapped is that you assign a value of -1. ScANVI and similar models expect a value of n_labels (last integer) for these entries. Do you have any preference on how to adjust it (likely in the on_before_batch_transfer call?

Whatever works i think.

>We need a smaller file than the current one for testing, currently ln.Collection.get(name="covid_normal_lung. Additionally, we need access to count data outside of adata.raw.X.

Hm, `MappedCollection` can't actually access .`raw` for now, only `.X`, .layers and `.obsm`. Yes, we can make a smaller collection of `anndata` files for testing.

**Comment by ori-kron-wis** [comment]
Hey Guys,

is this should be still working with the most recent version of Lamindb and its requirements?:
https://lamin.ai/laminlabs/cellxgene/transform/d1kl7wobCO1H0005?filter[and][0][or][0][_branch_code][eq]=1&filter[and][1][or][0][is_latest][eq]=true

For me Im getting :
```
collection = ln.Collection.get(name="covid_normal_lung")
lamindb.models.collection.Collection.DoesNotExist
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/opt/miniconda3/envs/scvi/lib/python3.12/site-packages/lamindb/models/record.py", line 497, in get
    return QuerySet(model=cls).get(idlike, **expressions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/scvi/lib/python3.12/site-packages/lamindb/models/query_set.py", line 651, in get
    return get(self, idlike, **expressions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/scvi/lib/python3.12/site-packages/lamindb/models/query_set.py", line 234, in get
    raise registry.DoesNotExist from registry.DoesNotExist
lamindb.models.collection.Collection.DoesNotExist
```

**Comment by falexwolf** [comment]
I suspect you're not connected to the `laminlabs/cellxgene` instance but running this on a local instance.

If the later is true, you have to run
```
ln.Collection.using("laminlabs/cellxgene").get(name="covid_normal_lung")
```

**Comment by ori-kron-wis** [comment]
Thanks, Alex, its working now.

**Comment by falexwolf** [comment]
For a unit test without benchmarking aspirations, I'd recommend something like this: https://github.com/laminlabs/lamindb/blob/6b09f64bdb8a395cd1c541a4e83743ff2833d63e/tests/core/test_collection.py#L167-L194

We have a few more collections that we used for the [blog post](https://blog.lamin.ai/arrayloader-benchmarks) last year: https://lamin.ai/laminlabs/arrayloader-benchmarks/collections. But none of them is very small. Same here: https://lamin.ai/laminlabs/cellxgene/collections

If you provide your Lamin handle, @ori-kron-wis, I could also make you a collaborator of both `arrayloader-benchmarks` and `cellxgene`, and you could add collections for testing and benchmarking yourself. ☺ 

Also: We're working on a follow-up to the blog post on benchmarking and would love to have you be a part of it, if you're interested. Let me know if you're down to discuss or simply book here: https://calendly.com/falexwolf/45flex

**Comment by ori-kron-wis** [comment]
Thanks, @falexwolf , see the updated PR with the unit test and well as several additional features for the scvi MappedCollectionDataModule for Lamin: 
several other features are still missing.

re the  Lamin handle, how do I export it? I do plan to make a real-life data scvi-tools tutorial on this.

**Comment by falexwolf** [comment]
> Thanks, @falexwolf , see the updated PR with the unit test and well as several additional features for the scvi MappedCollectionDataModule for Lamin: https://github.com/scverse/scvi-tools/pull/2932 several other features are still missing.

Great!

> re the Lamin handle, how do I export it?

Apologies. I'm not sure whether I understand the question. Your Lamin handle is your username on lamin.ai -- you can choose whatever, e.g., `ori-kron-wis`

**Comment by falexwolf** [comment]
Wow, that's awesome! I'll DM you on Zulip re publicizing it. ☺
