### ISSUE TITLE
Import fails with Python 3.10 and Homebrew

### ISSUE THREAD

**Issue by lebovic** [laminlabs/lamindb#217]
Install via `pip` succeeds, but `import lamindb` fails on Python 3.10 with Homebrew.

To reproduce:

1.
```
% pip install lamindb
```
(Using a MacBook Pro with an M1 Pro chip)

2. 
```

% python3
>>> import lamindb
```

Produces:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.10/site-packages/lamindb/__init__.py", line 20, in <module>
    from . import _check_versions
  File "/opt/homebrew/lib/python3.10/site-packages/lamindb/_check_versions.py", line 1, in <module>
    from bioreadout import __version__ as bioreadout_v
  File "/opt/homebrew/lib/python3.10/site-packages/bioreadout/__init__.py", line 18, in <module>
    from ._efo import EFO, readout  # noqa
  File "/opt/homebrew/lib/python3.10/site-packages/bioreadout/_efo.py", line 4, in <module>
    from bionty import EntityTable, Ontology
  File "/opt/homebrew/lib/python3.10/site-packages/bionty/__init__.py", line 40, in <module>
    from ._gene import Gene
  File "/opt/homebrew/lib/python3.10/site-packages/bionty/_gene/__init__.py", line 1, in <module>
    from ._core import Gene
  File "/opt/homebrew/lib/python3.10/site-packages/bionty/_gene/_core.py", line 8, in <module>
    from .._table import EntityTable, _todict
  File "/opt/homebrew/lib/python3.10/site-packages/bionty/_table.py", line 8, in <module>
    from ._ontology import Ontology
  File "/opt/homebrew/lib/python3.10/site-packages/bionty/_ontology.py", line 5, in <module>
    import pronto
  File "/opt/homebrew/lib/python3.10/site-packages/pronto/__init__.py", line 24, in <module>
    from .definition import Definition
  File "/opt/homebrew/lib/python3.10/site-packages/pronto/definition.py", line 5, in <module>
    from .xref import Xref
  File "/opt/homebrew/lib/python3.10/site-packages/pronto/xref.py", line 6, in <module>
    import fastobo
ImportError: dlopen(/opt/homebrew/lib/python3.10/site-packages/[fastobo.cpython-310-darwin.so](http://fastobo.cpython-310-darwin.so/), 0x0002): tried: '/opt/homebrew/lib/python3.10/site-packages/[fastobo.cpython-310-darwin.so](http://fastobo.cpython-310-darwin.so/)' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/[fastobo.cpython-310-darwin.so](http://fastobo.cpython-310-darwin.so/)' (no such file), '/usr/lib/[fastobo.cpython-310-darwin.so](http://fastobo.cpython-310-darwin.so/)' (no such file)
```

**Comment by Zethson** [comment]
Bionty is not a required dependency of lamindb anymore so this should be fixed
