### ISSUE TITLE
Remove `.from_values` from `Feature`

### ISSUE THREAD

**Issue by Zethson** [laminlabs/lamindb#2249]
### Add a description

https://laminlabs.slack.com/archives/C07DB677JF6/p1733229346107939

It is not possible so it should not be in the API let alone in the example section of the docstring (I removed it).

**Comment by falexwolf** [comment]
Alternative is to re-enable the default values that were possible in `from_values()`. When we still had them, this was valid.

Problem is that `from_values()` is part of `CanCurate` which dictates most of the Feature API; so, it's not 100% straightforward to remove it.

Maybe we should re-enable the defaults so that this becomes meaningful again.

**Comment by falexwolf** [comment]
`Feature.from_values()` works for its primary usecase: loading feature records from the database. Only if one passes `create=True`, one gets a clear error:

```python
>>> features = ln.Feature.from_values(["f1", "f2"], create=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/falexwolf/work/repos/laminhub/rest-hub/sub/lamindb/lamindb/models/can_curate.py", line 613, in from_values
    return _from_values(
           ^^^^^^^^^^^^^
  File "/Users/falexwolf/work/repos/laminhub/rest-hub/sub/lamindb/lamindb/models/_from_values.py", line 40, in _from_values
    registry(**{field.field.name: value}, **create_kwargs)
  File "/Users/falexwolf/work/repos/laminhub/rest-hub/sub/lamindb/lamindb/models/feature.py", line 894, in __init__
    kwargs = process_init_feature_param(args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/falexwolf/work/repos/laminhub/rest-hub/sub/lamindb/lamindb/models/feature.py", line 569, in process_init_feature_param
    raise ValidationError(
lamindb.errors.ValidationError: Please pass dtype, one of {'dict', 'path', 'datetime', 'num', 'str', 'cat', 'bool', 'int', 'date', 'float', 'object'} or a composed categorical dtype
```

I don't think we have an immediate action here.
