### ISSUE TITLE
ln.add fails with files that contain "?" (and "&") characters in their names

### ISSUE THREAD

**Issue by Zethson** [laminlabs/lamindb#608]
See discussion on Slack.

I ran into 

```
Traceback (most recent call last):
  File "/home/zeth/PycharmProjects/bionty/scripts/upload_new_ontologies.py", line 64, in <module>
    _run_upload(instance="lukas-bionty-test", check_github=False)
  File "/home/zeth/PycharmProjects/bionty/scripts/upload_new_ontologies.py", line 61, in _run_upload
    _upload_ontology_artifacts(instance=instance, entity_to_latest_ontology=entity_to_latest_ontology)
  File "/home/zeth/PycharmProjects/bionty/scripts/upload_new_ontologies.py", line 52, in _upload_ontology_artifacts
    ss.add(ontology_ln_file)
  File "/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/lamindb/dev/db/_session.py", line 55, in add
    return add(record=record, use_fsspec=use_fsspec, **fields)
  File "/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/lamindb/dev/db/_add.py", line 131, in add
    raise RuntimeError(error_message)
RuntimeError: An error occured. No entries were uploaded or committed to the database. See error message below.

maximum recursion depth exceeded in __instancecheck__
```

for a file named

`human_clo_2022-03-21_CellLine___download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb`.

After removing the `?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb` it worked flawlessly again. When playing around with stuff I also removed any "&" characters just in case. These might also lead to failures. I didn't verify this yet.

**Comment by Zethson** [comment]
I cannot reproduce this anymore:

```
arti = ln.Artifact("/tmp/human_clo_2022-03-21_CellLine___download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb")
arti.save()
arti
```

seems to work just fine
